credentials:
  usernames:
    curium:
      email: curium@gmail.com
      name: Team Curium
      password: '123456'  # This should be a hashed password
cookie:
  expiry_days: 0
  key: cookie_signature_key
  name: cookie_name
preauthorized:
  usernames:
  - curium
